---
title: "compartmental model"
author: "Dan Weinberger"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(outbreaks)
library(tidyverse)
library(rstan)
library(gridExtra)
rstan_options (auto_write = TRUE)
options (mc.cores = parallel::detectCores ())
set.seed(3) # for reproductibility
```
 
 Follows case study of https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html


```{r}
# time series of cases
cases <- influenza_england_1978_school$in_bed  # Number of students in bed

# total count
N <- 763;

# times
n_days <- length(cases) 
t <- seq(0, n_days, by = 1)
t0 = 0 
t <- t[-1]

#initial conditions
i0 <- 1
s0 <- N - i0
r0 <- 0
y0 = c(S = s0, I = i0, R = r0)

# data for Stan
data_sir <- list(n_days = n_days, y0 = y0, t0 = t0, ts = t, N = N, cases = cases)

# number of MCMC steps
niter <- 2000

```

```{r}
model <- stan_model("sir_negbin.stan")

```

```{r}
fit_sir_negbin <- sampling(model,
                data = data_sir,
                iter = niter,
                chains = 4)

```

```{r}
pars=c('beta', 'gamma')
print(fit_sir_negbin, pars = pars)

```

```{r}
stan_dens(fit_sir_negbin, pars = pars, separate_chains = TRUE)

```


 
 